M48
; DRILL file KiCad 10.0.5 date 2026-08-27T14:46:01
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-27T14:46:01+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X150.545Y-59.605
X156.325Y-59.605
T2
X129.0Y-63.54
X129.27Y-83.5
X139.16Y-63.54
X139.43Y-83.5
T3
X134.08Y-63.54
X134.35Y-83.5
M30
