M48
; DRILL file KiCad 10.0.5 date 2026-08-17T17:14:10
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-17T17:14:10+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X155.5Y-68.0
X161.28Y-68.0
T2
X117.73Y-93.54
X117.92Y-73.5
X127.89Y-93.54
X128.08Y-73.5
T3
X122.81Y-93.54
X123.0Y-73.5
M30
